installation of pandas

In [ ]:
pip install pandas

Import the required module

#Customized indexes

In [62]:
import pandas as pd

In [23]:
series_scalar = pd.Series(10 , index=['a','b','c','d','e','f'])
print(series_scalar)

a    10
b    10
c    10
d    10
e    10
f    10
dtype: int64

#Default indexes

```
# This is formatted as code
```

In [18]:
data = [10,20,30,40,50]
series_list = pd.Series(data)
print(series_list)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [19]:
type(series_list)

pandas.core.series.Series

#Load dataset

In [9]:
customers_df = pd.read_excel('/content/customers.xlsx')
products_df = pd.read_excel('/content/products.xlsx')
purchases_df = pd.read_excel('/content/purchases.xlsx')

In [11]:
#displays the top 5 records in a customer data frame
customers_df.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

#Attributes in series

In [20]:
series_list

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [22]:
data = ['New delhi', 'WashingtonDC', 'London','Paris']
index = ['India', 'USA','UK','France']
series_capital_country = pd.Series(data, index = index)
series_capital_country

India        New delhi
USA       WashingtonDC
UK              London
France           Paris
dtype: object

In [23]:
type(series_capital_country)

pandas.core.series.Series

In [24]:
series_capital_country.index

Index(['India', 'USA', 'UK', 'France'], dtype='object')

In [25]:
series_capital_country.values

array(['New delhi', 'WashingtonDC', 'London', 'Paris'], dtype=object)

In [26]:
series_capital_country.dtype

dtype('O')

In [27]:
series_capital_country.shape

(4,)

In [28]:
series_capital_country.ndim

1

In [29]:
series_capital_country.is_unique

True

#METHODS IN SERIES --

In [34]:
marks = [85, 90, 78, 92 , 88]
students = ['gopal','Aashish' ,'Adarsh', 'Akansha','Khushboo']
series_students_marks = pd.Series(marks, index = students)
print(series_students_marks)

gopal       85
Aashish     90
Adarsh      78
Akansha     92
Khushboo    88
dtype: int64

DISPLAY TOP 2 RECORDS IN THE SERIES

In [35]:
series_students_marks.head(2)

gopal      85
Aashish    90
dtype: int64

In [36]:
#display the bottom 2 records in the series
series_students_marks.tail(2)

Akansha     92
Khushboo    88
dtype: int64

Summary of the descreptive stats

In [37]:
series_students_marks.describe()

count     5.000000
mean     86.600000
std       5.458938
min      78.000000
25%      85.000000
50%      88.000000
75%      90.000000
max      92.000000
dtype: float64

value_counts() ->returns a series containing the count of unique values

In [38]:
series_students_marks.value_counts()

85    1
90    1
78    1
92    1
88    1
Name: count, dtype: int64

In [39]:
#sort_values()
series_students_marks.sort_values()

Adarsh      78
gopal       85
Khushboo    88
Aashish     90
Akansha     92
dtype: int64

In [44]:
series_students_marks.sort_values(ascending = False) #gives desending values

Akansha     92
Aashish     90
Khushboo    88
gopal       85
Adarsh      78
dtype: int64

In [48]:
# drop() - removes the specified index or column from the series/data frame
series_students_marks.drop('gopal', inplace=True)
print(series_students_marks)

Aashish     90
Adarsh      78
Akansha     92
Khushboo    88
dtype: int64

In [49]:
series_students_marks

Aashish     90
Adarsh      78
Akansha     92
Khushboo    88
dtype: int64

In [ ]:
series_v1 = series_students_marks.drop('gopal') # in this case orignal data structure is not changed changes are made in new data structure series_v1

MISSING VALUES IN SERIES

---

In [52]:
#HOW MANY MISSING VALUES ARE THERE IN DATA FRAME
missing_count = customers_df.isnull().sum()
print(missing_count)

id                 0
first_name         0
last_name          0
email            122
gender            43
street_num       262
street_name       37
street_suffix     37
city              79
state             80
postcode         157
dtype: int64

#Mathematical Operations in Series
Nan = not a number is a special floating -point value used to represent missing or undefined data in a dataset

In [57]:
series_1 = pd.Series([1,2,3,4,5] , index = ['a','b','c','d','e'])
series_2 = pd.Series([10,20,-30,40,-50] , index = ['z','y','a', 'c', 'e'])
print(series_1)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [72]:
print(series_2)

z    10
y    20
a   -30
c    40
e   -50
dtype: int64

In [71]:
result_addition = series_1 + series_2
print(result_addition)

a   -29.0
b     NaN
c    43.0
d     NaN
e   -45.0
y     NaN
z     NaN
dtype: float64

In [70]:
arr3 = np.array([1,2,3,4,5])
arr4 = np.array([4,5,7,9])
result = arr3 + arr4
print(result)
#in case of numpy arrays it will show error but in case of series it will show Nan

ValueError: operands could not be broadcast together with shapes (5,) (4,)

In [ ]:
#Data imputation - filling Nan values with '0' or mean or median is called Data imputation
#if the percentage of nan value is very less then in that case we drop all nan values

In [74]:
result = result_addition.fillna(0)
print(result)

a   -29.0
b     0.0
c    43.0
d     0.0
e   -45.0
y     0.0
z     0.0
dtype: float64

In [75]:
#drop all missing values
result_addition_dropped = result_addition.dropna()
print(result_addition_dropped)

a   -29.0
c    43.0
e   -45.0
dtype: float64

In [76]:
#Multiplication of two Series
result_multiplication = series_1 * series_2
print(result_multiplication)

a    -30.0
b      NaN
c    120.0
d      NaN
e   -250.0
y      NaN
z      NaN
dtype: float64

In [77]:
#division of 2 series
result_division = series_1 / series_2
print(result_division)

a   -0.033333
b         NaN
c    0.075000
d         NaN
e   -0.100000
y         NaN
z         NaN
dtype: float64

#DATA FRAME

In [79]:
purchases_df.head()

,Unnamed: 0,id,purch_date,customer_num,product_num,amount,paid
0,0,1,2019-01-03 00:00:00,823,27,12,$568.92
1,1,2,2019-01-03 00:00:00,606,28,14,$395.36
2,2,3,2019-01-03 00:00:00,955,9,17,$510.17
3,3,4,2019-01-03 00:00:00,577,19,3,$68.49
4,4,5,2019-01-03 00:00:00,429,8,18,$759.42

In [80]:
customers_df.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

In [86]:
# drop the column named 'Unnamed: 0' from the above products_df and purchases_df data frame
purchases_df.drop(columns=['Unnamed: 0'], errors='ignore', inplace=True)
products_df.drop(columns=['Unnamed: 0'], errors='ignore', inplace=True)

In [87]:
purchases_df.head()

   id           purch_date  customer_num  product_num  amount     paid
0   1  2019-01-03 00:00:00           823           27      12  $568.92
1   2  2019-01-03 00:00:00           606           28      14  $395.36
2   3  2019-01-03 00:00:00           955            9      17  $510.17
3   4  2019-01-03 00:00:00           577           19       3   $68.49
4   5  2019-01-03 00:00:00           429            8      18  $759.42

In [88]:
products_df.head()

   id                           product    cost   company
0   1              Liners - Baking Cups   $6.36  Skipfire
1   2        Nori Sea Weed - Gold Label  $85.74   Dynazzy
2   3                Bar Bran Honey Nut  $65.40      Ntag
3   4        Soup - Campbells Beef Stew  $68.16  Photojam
4   5  Wine - Shiraz Wolf Blass Premium  $87.39      Eare

In [89]:
#iloc vs loc
customers_df.shape

(1000, 11)

In [90]:
customers_df.iloc[4:11, 1:3] #iloc is used for default indexing

    first_name   last_name
4      Mikaela    Althorpe
5    Magdalena      Cullip
6     Marietta      Heball
7         Tine   McSperrin
8   Enrichetta  de Villier
9         Sari     Poulden
10      Natale     Martina

In [93]:
customers_df.loc[4:11, ['first_name','' ]]

4        Mikaela
5      Magdalena
6       Marietta
7           Tine
8     Enrichetta
9           Sari
10        Natale
11          Noni
Name: first_name, dtype: object

#Two ways to access the subset of a given data frame

In [95]:
#filtering purpose
male_customers = customers_df[customers_df['gender'] == 'Male']
print(male_customers)

       id first_name    last_name                           email gender  \
0       1     Romain    Southcott       rsouthcott0@clickbank.net   Male
1       2     Cosimo    Molyneaux           cmolyneaux1@wiley.com   Male
3       4     Roarke   Pankettman          rpankettman3@wiley.com   Male
10     11     Natale      Martina         nmartinaa@wordpress.com   Male
12     13      Mikol      MacWhan             mmacwhanc@patch.com   Male
..    ...        ...          ...                             ...    ...
984   985     Tailor      Sealeaf              tsealeafrc@irs.gov   Male
986   987       Eric    Mountford       emountfordre@blogspot.com   Male
997   998      Tobit         Birt                             NaN   Male
998   999     Issiah  Standbrooke  istandbrookerq@yellowpages.com   Male
999  1000     Elmore       Malpas                             NaN   Male

     street_num   street_name street_suffix       city           state  \
0           1.0     Trailsway          Road  San Diego      California
1           NaN           NaN           NaN    El Paso           Texas
3          74.0          Debs         Point    Memphis       Tennessee
10        221.0      Sauthoff          Pass  Bradenton         Florida
12          9.0   Eagle Crest        Center      Bronx        New York
..          ...           ...           ...        ...             ...
984         NaN  Summer Ridge          Pass   Beaufort  South Carolina
986         NaN           6th         Court  Las Vegas          Nevada
997         2.0         Basil          Road  Waterbury     Connecticut
998         NaN       Kenwood         Drive   Savannah         Georgia
999       205.0       Farwell          Park    Atlanta         Georgia

     postcode
0     92127.0
1         NaN
3     38150.0
10    34205.0
12    10469.0
..        ...
984   29905.0
986   89125.0
997    6721.0
998   31405.0
999   30386.0

[485 rows x 11 columns]

In [96]:
male_customers

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
10,11,Natale,Martina,nmartinaa@wordpress.com,Male,221.0,Sauthoff,Pass,Bradenton,Florida,34205.0
12,13,Mikol,MacWhan,mmacwhanc@patch.com,Male,9.0,Eagle Crest,Center,Bronx,New York,10469.0
...,...,...,...,...,...,...,...,...,...,...,...
984,985,Tailor,Sealeaf,tsealeafrc@irs.gov,Male,NaN,Summer Ridge,Pass,Beaufort,South Carolina,29905.0
986,987,Eric,Mountford,emountfordre@blogspot.com,Male,NaN,6th,Court,Las Vegas,Nevada,89125.0
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

In [98]:
purchases_df.head()

   id           purch_date  customer_num  product_num  amount     paid
0   1  2019-01-03 00:00:00           823           27      12  $568.92
1   2  2019-01-03 00:00:00           606           28      14  $395.36
2   3  2019-01-03 00:00:00           955            9      17  $510.17
3   4  2019-01-03 00:00:00           577           19       3   $68.49
4   5  2019-01-03 00:00:00           429            8      18  $759.42

Acess only 2, 3 ,4th row also only 'product_num' and 'paid' column

In [99]:
purchases_df.loc[2:4, ['product_num', 'paid']]

   product_num     paid
2            9  $510.17
3           19   $68.49
4            8  $759.42

In [100]:
purchases_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            6000 non-null   int64
 1   purch_date    6000 non-null   object
 2   customer_num  6000 non-null   int64
 3   product_num   6000 non-null   int64
 4   amount        6000 non-null   int64
 5   paid          6000 non-null   object
dtypes: int64(4), object(2)
memory usage: 281.4+ KB

In [ ]:
#renaming row label of a dataframe

In [101]:
customers_df.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

In [102]:
customers_df.rename(index = {0: 'first_customoer'}, inplace=True)
customers_df

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
first_customoer,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

In [103]:
customers_df.rename(columns={'street_name': 'street_address'}, inplace=True)
customers_df.head()

,id,first_name,last_name,email,gender,street_num,street_address,street_suffix,city,state,postcode
first_customoer,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

Finding the unique value

In [104]:
unique_gender = customers_df['gender'].unique()
print(unique_gender)

['Male' 'Female' nan]

#count of no of unique values

In [107]:
unique_gender_count = customers_df['gender'].nunique()
print(unique_gender_count)

2