Installation of the pandas Module

In [ ]:
#pip install pandas

In [ ]:
#import the required module

In [ ]:
import pandas as pd

Custmized indexes

In [ ]:
import pandas as pd
Series_scalar = pd.Series(10, index=['a','b','c','d','e','f'])
print(Series_scalar)

a    10
b    10
c    10
d    10
e    10
f    10
dtype: int64

Labelled indexes

In [ ]:
data = [10,20,30,40,50]
series_list = pd.Series(data)
print(series_list)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
type(series_list)

In [ ]:
customer_df = pd.read_excel('/customers.xlsx')
products_df = pd.read_excel('/products.xlsx')
purchased_df = pd.read_excel('/purchases.xlsx')

Display the top 5 record in the customer dataframe

In [ ]:
customer_df.head() # by default it displays 5 records

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

Attributed in Series

In [ ]:
data = ['New delhi', 'Washington' , 'London' , 'Paris']
index = ['India', 'USA', 'UK', 'France']

series_capital_country = pd.Series(data, index = index)
print(series_capital_country)

India      New delhi
USA       Washington
UK            London
France         Paris
dtype: object

In [ ]:
type(series_capital_country)

pandas.core.series.Series

In [ ]:
series_list

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
series_capital_country.index

Index(['India', 'USA', 'UK', 'France'], dtype='object')

In [ ]:
series_capital_country.values

array(['New delhi', 'Washington', 'London', 'Paris'], dtype=object)

In [ ]:
series_capital_country.dtype

dtype('O')

In [ ]:
series_capital_country.ndim

1

In [ ]:
series_capital_country.shape

(4,)

In [ ]:
series_capital_country.is_unique

True

Methods in Series

In [ ]:
marks = [ 95, 98,78,92,88]
students = ['Adarsh','Ashish', 'Anushka', 'khusboo','Akansha']
series_student_marks = pd.Series(marks, index = students)
print(series_student_marks)

Adarsh     95
Ashish     98
Anushka    78
khusboo    92
Akansha    88
dtype: int64

Display top 2 reports  in the series

In [ ]:
series_student_marks.head(2)

Adarsh    95
Ashish    98
dtype: int64

Display the botton 2 records in the series

In [ ]:
series_student_marks.tail(2)

khusboo    92
Akansha    88
dtype: int64

Summary of the descriptive statistics

In [ ]:
series_student_marks.describe()

count     5.000000
mean     90.200000
std       7.758866
min      78.000000
25%      88.000000
50%      92.000000
75%      95.000000
max      98.000000
dtype: float64

value_counts() -> returns a series containing the count of unique values

In [ ]:
series_student_marks.value_counts()

95    1
98    1
78    1
92    1
88    1
Name: count, dtype: int64

sort values

In [ ]:
series_student_marks.sort_values()

Anushka    78
Akansha    88
khusboo    92
Adarsh     95
Ashish     98
dtype: int64

In [ ]:
series_student_marks.sort_values(ascending=False)

Ashish     98
Adarsh     95
khusboo    92
Akansha    88
Anushka    78
dtype: int64

drop() - > removes the specified index or columns from the series dataframe

In [ ]:
print(series_student_marks.drop('Adarsh', errors='ignore'))

Ashish     98
Anushka    78
khusboo    92
Akansha    88
dtype: int64

In [ ]:
series_student_marks

Ashish     98
Anushka    78
khusboo    92
Akansha    88
dtype: int64

Missing values in Series

In [52]:
missing_count = series_student_marks.isnull().sum()
print(missing_count)

0

Missing Values in dataframe

In [53]:
missing_count = customer_df.isnull().sum()
print(missing_count)

id                 0
first_name         0
last_name          0
email            122
gender            43
street_num       262
street_name       37
street_suffix     37
city              79
state             80
postcode         157
dtype: int64

Mathematical Operations in Series
NaN => Not a Number =>Missing Values

In [56]:
import pandas as pd

series_1 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
series_2 = pd.Series([10, 20, 30, 40, 50], index=['z', 'y', 'a', 'c', 'e'])

print(series_1)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [57]:
print(series_2)

z    10
y    20
a    30
c    40
e    50
dtype: int64

In [58]:
result_addition = series_1 + series_2
print(result_addition)

a    31.0
b     NaN
c    43.0
d     NaN
e    55.0
y     NaN
z     NaN
dtype: float64

In [61]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
print(arr1 + arr2)

[11 22 33 44 55]

In [62]:
result = result_addition.fillna(0)
print(result)

a    31.0
b     0.0
c    43.0
d     0.0
e    55.0
y     0.0
z     0.0
dtype: float64

In [63]:
result_addition_dropped = result_addition.dropna()
print(result_addition_dropped)

a    31.0
c    43.0
e    55.0
dtype: float64

Multiplication of two Series

In [64]:
result_multiplication = series_1 * series_2
print(result_multiplication)

a     30.0
b      NaN
c    120.0
d      NaN
e    250.0
y      NaN
z      NaN
dtype: float64

Division of two Series

In [65]:
result_division = series_1 / series_2
print(result_division)

a    0.033333
b         NaN
c    0.075000
d         NaN
e    0.100000
y         NaN
z         NaN
dtype: float64

DataFrame

In [66]:
products_df.head()

   Unnamed: 0  id                           product    cost   company
0           0   1              Liners - Baking Cups   $6.36  Skipfire
1           1   2        Nori Sea Weed - Gold Label  $85.74   Dynazzy
2           2   3                Bar Bran Honey Nut  $65.40      Ntag
3           3   4        Soup - Campbells Beef Stew  $68.16  Photojam
4           4   5  Wine - Shiraz Wolf Blass Premium  $87.39      Eare

In [71]:
purchased_df.head()

,Unnamed: 0,id,purch_date,customer_num,product_num,amount,paid
0,0,1,2019-01-03 00:00:00,823,27,12,$568.92
1,1,2,2019-01-03 00:00:00,606,28,14,$395.36
2,2,3,2019-01-03 00:00:00,955,9,17,$510.17
3,3,4,2019-01-03 00:00:00,577,19,3,$68.49
4,4,5,2019-01-03 00:00:00,429,8,18,$759.42

Drop the column 'Unamed: 0' from the above products_df and purchase_df dataframe